### ISSUE TITLE
Adding support for stack depth calculation

### ISSUE THREAD

**Issue by MatthieuDartiailh** [haypo/bytecode#4]
Hi,  
I am interested in porting the stack depth calculation found in byteplay to bytecode. Before starting do you have any pointer to give me about this ? 
Thanks

**Comment by serhiy-storchaka** [comment]
What are the differences between this and dis.stack_effect()?

**Comment by MatthieuDartiailh** [comment]
dis.stack_effect compute the impact on the stack of a single opcode.
The goal here is to compute the proper stack depth for a given code object and pass it to CodeType. This is done by going through all the opcodes of the stack objects and explore all the branches.

**Comment by MatthieuDartiailh** [comment]
Closed by #8
